#### Method 1

In [1]:
#importing the opencv module in the code
import cv2
#storing the image in a variable
original = cv2.imread('./IMG_3333.png')
  
#transforming from BGR to RGB
convert = cv2.cvtColor(original, cv2.COLOR_BGR2RGB)
#writing the image to a file 
cv2.imwrite('opncv_sample.png', convert)
#printing the type of the converted image
print ("The image has been converted from .png to ",type(convert))

The image has been converted from .png to  <class 'numpy.ndarray'>


#### Method 2

In [3]:
# Importing the required modules
from PIL import Image
from numpy import asarray 
#loading the image 
original = Image.open('./IMG_3333.png')
# using the asarray() function
# converting PIL images into NumPy arrays
numpydataarr = asarray(original) 
# printing the type of the image after conversion
print("The type after conversion is:",type(numpydataarr))
# displaying the shape of the image
print("dimensions of the array", numpydataarr.shape)
#Printing the pixel information
print("The pixel information is=")
print(numpydataarr) 

The type after conversion is: <class 'numpy.ndarray'>
dimensions of the array (4032, 3024, 3)
The pixel information is=
[[[69 52 32]
  [69 52 32]
  [69 52 32]
  ...
  [68 51 31]
  [67 52 33]
  [67 52 33]]

 [[69 52 32]
  [69 52 32]
  [69 52 32]
  ...
  [68 51 31]
  [67 52 33]
  [67 52 33]]

 [[69 52 32]
  [69 52 32]
  [69 52 32]
  ...
  [68 51 31]
  [67 52 33]
  [67 52 33]]

 ...

 [[67 51 38]
  [67 51 38]
  [67 51 38]
  ...
  [67 53 40]
  [66 54 42]
  [66 54 42]]

 [[65 51 40]
  [65 51 40]
  [65 51 40]
  ...
  [66 54 42]
  [64 54 44]
  [64 54 44]]

 [[65 51 40]
  [65 51 40]
  [65 51 40]
  ...
  [66 54 42]
  [64 54 44]
  [64 54 44]]]


#### Method 3

In [6]:
#importing required modules
from skimage import io
#storing the image in a variable and converting
imagenotoriginal = io.imread('./IMG_3333.png')
#displaying the type of the picture after conversion and other details
print("The type of the image now is=",type(imagenotoriginal))
print("The daatatype of the image is=",imagenotoriginal.dtype)
print("The dimensions of the original image are= ",imagenotoriginal.shape)


The type of the image now is= <class 'numpy.ndarray'>
The daatatype of the image is= uint8
The dimensions of the original image are=  (4032, 3024, 3)
